# Generated by Django 3.1.7 on 2021-06-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_access_level', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_info_table',
            },
        ),
    ]
